#----------------------------------
# Github Action part-1 - basics
#
# Copyleft (c) by ME
#----------------------------------
name: My-GitHubactions-Basics

on:  
  push:
    branches: [ main ]

jobs: 
  my_testing: 
    runs-on:  ubuntu-latest

    steps:
      - name: Print nice message Testing job
        run: echo "Hello world from Test!!"
      
      - name: Execute few commands
        run: |
          echo "Hello 1"
          echo "hello 2"

      - name: List current folder
        run: |
          ls -la
          uname -a

      - name: Git clone my repo
        uses: actions/checkout@v1

      - name: List current folder again
        run: |
          ls -la
          uname -a

  my_deploy:
    runs-on:  ubuntu-latest
    needs: my_testing

    steps:
      - name: Print nice message from Deploy job
        run: echo "Hello world from Deploy!"

      - name: List current folder
        run: |
          ls -la
          uname -a
