#----------------------------------
# Github Action part-1 - basics
#
# Copyleft (c) by ME
#----------------------------------
name: My-GitHubactions-Basics
env:
  APPLICATION_NAME:  "MyFlaskApp"
  DEPLOY_PACKAGE_NAME:  "flask-app-ver-${{ github.sha }}"


on:  
  push:
    branches: 
    - main

jobs: 
  my_testing: 
    runs-on:  ubuntu-latest

    steps:
      - name: Print nice message Testing job
        run: echo "Hello world from Test!!"
      
      - name: Execute few commands 1
        run: |
          echo "Hello 1"
          echo "hello 2"
          echo "Printing Global ENV variable ${{ env.DEPLOY_PACKAGE_NAME }}"

      - name: List current folder
        run: |
          ls -la
          uname -a

      - name: Git clone my repo
        uses: actions/checkout@v1

      - name: List current folder again
        run: |
          ls -la
          uname -a

  my_deploy:
    runs-on:  ubuntu-latest
    needs: my_testing
    env:
      VAR1: "Job variable 1"
      VAR2: "Job variable 2"

    steps:
      - name: Print nice message from Deploy job
        run: echo "Hello world from Deploy!"

      - name: List current folder
        run: |
          uname -a
          ls -la

      - name: Printing some info
        run: echo "App name is ${{ env.APPLICATION_NAME }}"

      - name: Printing some more info
        run: |
          echo "Var1 =  ${{ env.VAR1 }}"
          echo "Var2 =  ${{ env.VAR2 }}"
          
      - name: Print super local env var
        run: echo "This is local variable $LOCAL_VAR1"
        env:
          LOCAL_VAR1: "Hello I am local variable"

      - name: Check if command exist
        run: aws --version

      - name: Check if ZIP exist
        run: zip --version
